<a href="https://colab.research.google.com/github/sriharsha1718/Pytorch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install torch

In [2]:
import torch
print(torch.__version__)

2.0.1+cu118


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [6]:
torch.cuda.memory_allocated()

0

In [7]:
import numpy as np

In [8]:
arr = np.array([3, 4, 5, 6])
arr

array([3, 4, 5, 6])

In [9]:
#Convert Numpy arrays to Tensors
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [10]:
tensors[:2]

tensor([3, 4])

In [11]:
tensors[2]

tensor(5)

In [12]:
tensors[1:4]

tensor([4, 5, 6])

In [13]:
#Array and Tensors uses same memory location
tensors[3] = 400
tensors

tensor([  3,   4,   5, 400])

In [14]:
arr

array([  3,   4,   5, 400])

In [15]:
#To prevent this from happening
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 400])

In [16]:
tensor_arr[3] = 500
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 500])
[  3   4   5 400]


In [17]:
#Zeros and Ones
z = torch.zeros(2,3, dtype=torch.int64)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [18]:
o = torch.ones(3,4, dtype=torch.float32)
print(o)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [19]:
np.arange(0,15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
a = torch.tensor(np.arange(0,15).reshape(5,3))

In [21]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [22]:
a[:,:]

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [23]:
a[:4,:3]

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [24]:
#Arithmetic Operation
a = torch.tensor([3, 4, 5], dtype=torch.float64)
b = torch.tensor([4, 5, 6], dtype=torch.float64)
print(a + b)

tensor([ 7.,  9., 11.], dtype=torch.float64)


In [25]:
torch.add(a,b)

tensor([ 7.,  9., 11.], dtype=torch.float64)

In [26]:
c = torch.zeros(3)
c

tensor([0., 0., 0.])

In [27]:
torch.add(a,b, out=c)
c

tensor([ 7.,  9., 11.])

In [28]:
#c.sum()
torch.add(a,b).sum()

tensor(27., dtype=torch.float64)

In [29]:
#Dot Product and Multiplication Operations
x = torch.tensor([3, 4, 5], dtype=torch.float64)
y = torch.tensor([4, 5, 6], dtype=torch.float64)

In [30]:
x.mul(y)

tensor([12., 20., 30.], dtype=torch.float64)

In [31]:
x.dot(y)

tensor(62., dtype=torch.float64)

In [32]:
#Matrix Multiplication
x = torch.tensor([[1,4,2], [1,5,5]], dtype=torch.float64)
y = torch.tensor([[5,7], [8,6], [9,11]], dtype=torch.float64)

In [33]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)

In [34]:
x.matmul(y)

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)

In [35]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)

In [36]:
x@y

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)