<a href="https://colab.research.google.com/github/sriharsha1718/Pytorch/blob/main/Pytorch1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Backpropagation using Pytorch
#y=x^2

import torch
x = torch.tensor(4.0, requires_grad=True)
x

tensor(4., requires_grad=True)

In [2]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [3]:
z = y.sum()
z

tensor(16., grad_fn=<SumBackward0>)

In [4]:
#Back Propogation y = 2*x
z.backward()

In [5]:
print(x.grad)

tensor(8.)


In [6]:
lst = [[2.,3.,1.],[4.,5.,3.], [7.,6.,4.]]
torch_input = torch.tensor(lst, requires_grad=True)
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [7]:
y = torch_input**3 + torch_input**2
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [8]:
z = y.sum()
z

tensor(1040., grad_fn=<SumBackward0>)

In [9]:
z.backward()

In [10]:
print(torch_input.grad)

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])
